---
title: 'Case Study 1: Birth Weight'
author: "Moriah Taylor, Faraz Yashar, AJ Eckmann, Audreya Metz, Naya Chen"
date: "9/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, function checking for installed packages, include=FALSE, echo=FALSE}
# Source for function: https://stackoverflow.com/questions/9341635/check-for-installed-packages-before-running-install-packages
pkgTest <- function(x)
  {
    if (!require(x,character.only = TRUE))
    {
      install.packages(x,repos = "http://cran.r-project.org", dep=TRUE)
        if(!require(x,character.only = TRUE)) stop("Package not found")
    }
  }
```

```{r}
# Load any necessary packages here
pkgTest("tidyr")
pkgTest("dplyr")
pkgTest("purrr")
pkgTest("tidyverse")
library(tidyr)
library(dplyr)
library(purrr)
library(tidyverse)
```

```{r}
# read in birth data with NAs
o_data = read.csv("data/Yr1116Birth.csv", na.strings=c("9","99", "9999"))
```

```{r}
# remove missing rows
birth_data = na.omit(o_data)

# convert to categorical variables
# SEX, CORES(residence), MRACER(race), MHISP(Hispanic origin)
birth_data = birth_data %>% mutate(
  SEX = as.factor(SEX),
  CORES = as.factor(CORES),
  MRACER = as.factor(MRACER),
  MHISP = as.factor(MHISP),
)

# function to convert numeric values to two-level categorical variables
# based on threshold
transform = function(data, cols, threshold) {
  for (i in 1:length(cols)) {
    col = cols[i]
    data[col] = as.factor(
      case_when(
        data[col] <= threshold ~ 0,
        data[col] > threshold ~ 1,
      )
    )
  }
  return(data)
}

# convert average #cig to categorical: smoke or not smoke
birth_data = transform(birth_data, c("CIGPN", "CIGFN", "CIGSN", "CIGLN"), 0)
# convert #pregancy to categorical: pregnant before or never
birth_data = transform(birth_data, c("PARITY"), 1)
glimpse(birth_data)
```

